version: "3"
services:
  gobm:
    build: .
    image: marugoshi/gobm
    container_name: gobm
    ports:
      - "8080:8080"
    volumes:
     - ".:/go/src/github.com/marugoshi/gobm"
    command: go run main.go