version: "3"
services:
  gobm:
    build: .
    image: marugoshi/gobm
    links:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - ".:/go/src/github.com/marugoshi/gobm"
    environment:
      DB_USER: root
      DB_PASS: password
      DB_HOST: mysql
      DB_NAME: gobm_d
    tty: true
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/log:/var/log/mysql"
      - "./mysql/conf:/etc/mysql/conf.d"
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci